server:
  port: 8764

eureka:
  client:
    service-url:
      defaultZone: ${HS_CMS_EUREKA_URI:http://localhost:8761/eureka}

spring:
  datasource:
    url: jdbc:postgresql://${HS_CMS_DATASOURCE_HOST}:${HS_CMS_DATASOURCE_PORT}/${HS_CMS_DATASOURCE_DATABASE}
    username: ${HS_CMS_DATASOURCE_USERNAME}
    password: ${HS_CMS_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: none
    show-sql: true

springdoc:
  api-docs:
    path: "/api-docs"
  swagger-ui:
    path: "/swagger-ui"

management:
  endpoints:
    web:
      exposure:
        include: "*"

#logging:
#  level:
#    org:
#      springframework:
#        security: DEBUG
#        web: DEBUG
#      hibernate: ERROR
